Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

ans->Ordinal encoding is typically used when there is an inherent order or ranking among the categories in the categorical feature.Label encoding is used when there is no inherent order or ranking among the categories in the categorical feature, and you simply want to convert them to numerical labels.

For example, in a real estate prediction model, you might use ordinal encoding for a feature like "Condition," where the categories are "Poor," "Fair," "Good," and "Excellent," as there is a clear ranking. However, for a feature like "Neighborhood," you would use label encoding, as there's no inherent order among different neighborhoods.

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

ans->Target Guided Ordinal Encoding is a method to convert categorical variables into ordinal labels based on their statistical relationship with the target variable in a supervised machine learning problem. It's useful when you want to capture the impact of categories on the target variable. For example, in customer churn prediction, you can use it to assign ordinal labels to contract types based on their association with churn rates, helping the model make better predictions.

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

ans->covariance is a statistical measure that quantifies how two variables change together. It's important in statistical analysis because it helps us understand the relationship between variables, whether it's positive or negative. However, it can be sensitive to variable scales and only captures linear relationships, so correlation coefficients are often preferred for more standardized and interpretable measures of association.


In [1]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])
covariance = np.cov(X, Y)[0, 1]
print("Covariance:", covariance)


Covariance: -2.5


Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [5]:
import pandas as pd
df=pd.DataFrame({
    'color' :['red', 'green', 'blue'],
    'Size' :['small', 'medium', 'large'],
    'material':['wood', 'metal', 'plastic']
})
df

color    Size material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [15]:
encoder.fit_transform(df[['color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [16]:
encoder.fit_transform(df[['Size']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [17]:
encoder.fit_transform(df[['material']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1])

The 'Color' column has been encoded as [2, 1, 0], where 'red' is 2, 'green' is 1, and 'blue' is 0.

The 'Size' column has been encoded as [2, 1, 0], where 'small' is 2, 'medium' is 1, and 'large' is 0.

The 'Material' column has been encoded as [2, 1, 0], where 'wood' is 2, 'metal' is 1, and 'plastic' is 0.

Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [20]:
age = [30, 35, 40, 45, 50]
income = [500, 600, 700, 750, 800]
education_level = [12, 16, 14, 18, 20]
data_matrix = np.array([age, income, education_level])
covariance_matrix = np.cov(data_matrix)
print(covariance_matrix)

[[6.250e+01 9.375e+02 2.250e+01]
 [9.375e+02 1.450e+04 3.250e+02]
 [2.250e+01 3.250e+02 1.000e+01]]


Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

ans-> binary encoding or label encoding for "Gender" because it has only two categories.

 ordinal encoding or target-guided ordinal encoding for "Education Level" because it has an ordered relationship

 one-hot encoding for "Employment Status" because it's a nominal categorical variable without an inherent order, and all categories are equally distant.

Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [24]:
temperature = [75, 80, 85, 90, 95]
humidity = [40, 45, 50, 55, 60]
data_matrix_continuous = np.array([temperature, humidity])
covariance_continuous = np.cov(data_matrix_continuous)
print(covariance_continuous)

[[62.5 62.5]
 [62.5 62.5]]
